### ISSUE TITLE
Heating/DWH activity - can be read?

### ISSUE THREAD

**Issue by rufik** [SmartHomeIntegrationTech/MQTTServices-Daikin#3]
I'd like to ask if is it possible to get information about:

1. heating - if unit is actively heating (compressor is running)?
2. DHW - if unit is heating up hot water?
3. Temperature of inlet/outlet water?
4. Backup heater is on?

**Comment by KarstenB** [comment]
1. You can check homie/daikin-heatingunit/spaceheating/1-operation-power which is either `on` or `standby`
2. Same for the water heating. 
3. In my unit you can also check the temperature of the water in the tank, but nothing more.
4. Nope

If you need more details, you will have to use the serial connection on the heating unit. The adapter simply does not return those values, sadly.
