### ISSUE TITLE
Integration to OpenHAB

### ISSUE THREAD

**Issue by misko903** [SmartHomeIntegrationTech/MQTTServices-Daikin#4]
Hello,
are you planning to integrate this into OpenHAB as an addon?
I dont know how to run the GUI on openhabian. The -d option finds the adapter. I am stucked then.

Thanks, this will be a killer function in my OpenHAB, when it will be working.

**Comment by KarstenB** [comment]
You don't have to run this on the openhabian, it can be any computer that is in the same network as the adapter. So try starting the GUI for configuration on your computer, then save the discovered settings to the PollingSettings.json. You can then transfer the jar and PollingSettings to openhabian to run it there with `-p`.

I was starting to work on an Openhab integration, but decided against continuing this effort. Openhab does not really like the dynamic nature of my channels and is rather annoying to code for. So you can easily discover the properties with the homie plugin.

**Comment by misko903** [comment]
OK, thanks, I have used other pi to generate file. Then I will transfer it to openhabian RPi... and run it after start with cron?
What do you mean by Homie plugin? I did not found an OpenHAB addon named like that. Or should I look somewhere else?
Thanks,
M.

**Comment by KarstenB** [comment]
You start as a service, so it runs continuously and does the scheduling itself. For easy integration, just use the https://www.openhab.org/addons/bindings/mqtt/ MQTT binding in openhab and it will automatically find it :)

**Comment by misko903** [comment]
OK, so after I generated `PollingSettings.json` I ran:
```
openhabian@openHABianDevice:~ $ java -jar daikin-0.0.3.jar -p                   [main] INFO org.eclipse.jetty.util.log - Logging initialized @1411ms to org.eclipse.jetty.util.log.Slf4jLog
mar 04, 2021 10:01:12 PM io.github.dschanoeh.homie_java.Homie lambda$0
INFO: --> init
mar 04, 2021 10:01:14 PM io.github.dschanoeh.homie_java.Homie lambda$0
INFO: --> ready
```
but the Thing has no Channels. I am using other MQTT Things too, so MQTT broker and stuff around should be configured OK.

My Thing configuration:
```
UID: mqtt:homie300:0106506a0b:daikin-heatingunit
label: Altherma3
thingTypeUID: mqtt:homie300
configuration:
  deviceid: daikin-heatingunit
  removetopics: false
  basetopic: homie
bridgeUID: mqtt:broker:0106506a0b
location: Chodba
```

How to make those channels working then?

**Comment by KarstenB** [comment]
Probably you simply need to stop and restart the Daikin jar as openhab only correctly configures homie things when they send their homie data (instead of using the retained data as everyone else does).

**Comment by misko903** [comment]
Tried - hit ctrl+c and ran the command again. No results. Any other idea?
do I need to set up ownerships?

**Comment by KarstenB** [comment]
Oh, I just realised in my other projects I am using homie 3.x convention, whereas this project already uses 4.x.... I didn't add it to my OpenHab since I directly pipe the data into influx and use graphana to visualise it. Let me quickly check if it is possible for OpenHab to still accept Homie 4.x somehow...

**Comment by misko903** [comment]
From OH Thing:
You need a configured Broker first. This thing represents a device, that follows the "MQTT Homie Convention" (Version 3.x).
and 
`thingTypeUID: mqtt:homie300`
looks like it is 3.x

**Comment by KarstenB** [comment]
It says 3.x or better. But unfortunately my bet is on this bug https://github.com/openhab/openhab-addons/issues/7252 as I see the dreaded "Caused by: java.lang.Exception: Did not receive mandatory topic value: homie/daikin-heatingunit/adapter/$name" exception. You may try to lower the number of channels in your PollingSettings and see if that works, but I am doubtful. I will investigate it a bit more...

**Comment by KarstenB** [comment]
I found the issue and fixed it in v0.0.4.

**Comment by misko903** [comment]
Thanks, I'll test it at the evening. Do I need to generate the JSON again?

One primitive question: how to run it as a service? Cron at start?

Thanks!

Dňa pi 5. 3. 2021, 10:09 Karsten Becker <notifications@github.com>
napísal(a):

**Comment by KarstenB** [comment]
No need to update the JSON, that should still work. For the service, I just added a section to the Readme regarding that. The best way is to use systemd.

**Comment by KarstenB** [comment]
I just re-uploaded the version 0.0.4 as I amended the homie-java library with some better handling for strings. For some reason it did not set the string $datatype which made the discovered channels in OH look ugly.

**Comment by misko903** [comment]
Hi Karsten,I have tested the new 0.0.4 on my OpenHABian with running the program:
```
openhabian@openHABianDevice:~ $ java -jar daikin-0.0.4.jar -p
[main] INFO org.eclipse.jetty.util.log - Logging initialized @1448ms to org.eclipse.jetty.util.log.Slf4jLog
mar 05, 2021 4:31:45 PM io.github.dschanoeh.homie_java.Homie lambda$0
INFO: --> init
mar 05, 2021 4:31:48 PM io.github.dschanoeh.homie_java.Homie lambda$0
INFO: --> ready
```
The Thing is discovered, but again, **it has no channels**.

> This thing has no channels. Either the thing type doesn't define channels, or they may be detected and appear later.

This is text conf of the Thing:
```
UID: mqtt:homie300:0106506a0b:daikin-heatingunit
label: daikin-heatingunit
thingTypeUID: mqtt:homie300
configuration:
  deviceid: daikin-heatingunit
  removetopics: false
  basetopic: homie
bridgeUID: mqtt:broker:0106506a0b
```

**Comment by KarstenB** [comment]
Can you maybe upload your PollingSettings.json somewhere and/or connect with a tool such as MQTT-Explorer and show the homie structure that was created?

**Comment by misko903** [comment]
I am connected to my OH server with MQTT-Explorer and i can see homie/daikin-heatingunit. 
Here the PollingSettings.json
[](https://drive.google.com/file/d/1jJn14igL3npLbhRCshHhGqcSbD2h7sH-/view?usp=sharing)

**Comment by KarstenB** [comment]
ok, the settings look fine. Can you run `mosquitto_sub -h localhost -t homie/daikin-heatingunit/# -d > channels.log` on your broker, or any other computer (and change localhost to your broker), and send me the channels.log?

**Comment by misko903** [comment]
https://drive.google.com/file/d/1OlVqpWpXEpTG4iucrhMZgBZxy8oS6JIB/view?usp=sharing

**Comment by KarstenB** [comment]
Ok, I can't see anything wrong (aside from the `homie/daikin-heatingunit/$state` being "LOST" which probably means that the polling was not running at the time you were capturing the dump) here from my point of view. The issue is probably on the the OpenHab/Configuration side of things. I don't think I can help you any further here. You may try a wild combination of checking the OH logs, restarting OH and the polling, adding and removing the Thing, but I don't see anything I could do from my side here.

**Comment by misko903** [comment]
OK. 
just for info, this is the tail -f from OH3:

```
2021-03-05 19:58:15.576 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'mqtt:homie300:0106506a0b:daikin-heatingunit' to inbox.
==> /var/log/openhab/events.log <==
2021-03-05 19:58:15.576 [INFO ] [openhab.event.InboxAddedEvent       ] - Discovery Result with UID 'mqtt:homie300:0106506a0b:daikin-heatingunit' has been added.
==> /var/log/openhab/openhab.log <==
2021-03-05 19:58:18.038 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler HomieThingHandler tried updating thing mqtt:homie300:0106506a0b:daikin-heatingunit although the handler was already disposed.
==> /var/log/openhab/events.log <==
==> /var/log/openhab/openhab.log <==
2021-03-05 19:58:31.887 [WARN ] [.mqtt.homie.internal.homie300.Device] - Could not subscribe
java.util.concurrent.CompletionException: java.lang.Exception: Did not receive mandatory topic value: homie/daikin-heatingunit/adapter/$name
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1423) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) [?:?]
	at org.openhab.binding.mqtt.generic.mapping.SubscribeFieldToMQTTtopic.timeoutReached(SubscribeFieldToMQTTtopic.java:166) [bundleFile:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.Exception: Did not receive mandatory topic value: homie/daikin-heatingunit/adapter/$name
	... 7 more
==> /var/log/openhab/events.log <==
2021-03-05 19:58:31.656 [INFO ] [openhab.event.InboxRemovedEvent     ] - Discovery Result with UID 'mqtt:homie300:0106506a0b:daikin-heatingunit' has been removed.
```

**Comment by KarstenB** [comment]
Are you sure you are using the 0.0.4 version? That should have fixed that. You can see from your log that it was there: `Client mosq-To3hHWb8oAlpDiTSfa received PUBLISH (d0, q0, r1, m0, 'homie/daikin-heatingunit/adapter/$name', ... (7 bytes))
Adapter`.

**Comment by misko903** [comment]
Tadaaa!
I have redownloaded the 0.0.4 version and now i see a lot of channels!

Thanks, problem solved :)
