### ISSUE TITLE
Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Daikin MQTT connector

### ISSUE THREAD

**Issue by Bettinaglio** [SmartHomeIntegrationTech/MQTTServices-Daikin#6]
I've got this in my startup log in home assistant 2022.3.3:

WARNING (SyncWorker_0) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Daikin MQTT connector

Thanks
Louis

**Comment by KarstenB** [comment]
Hi,
I am not the maintainer of the home assistant plugin. You may want to file this issue here https://github.com/jaakla/home-assistant-addons as I assume you're using that.

Hope that helps,
Karsten

**Comment by Bettinaglio** [comment]
Sorry and thanks a lot, Karsten. Postet to jaakla....
